import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, copyFileSync, mkdirSync, writeFileSync } from "fs";
import { resolve } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const args = process.argv.slice(2);
const prod = args.includes("production");

// Two editions from one source tree:
//   • full    → root main.js, sideloaded, includes the focus feature (BLE + face)
//   • catalog → dist-catalog/, submitted to the Obsidian store, focus excluded
// `catalog` flips INCLUDE_FOCUS off so esbuild strips the entire focus chain.
const catalog = args.includes("catalog");
const includeFocus = !catalog;
const outDir = catalog ? "dist-catalog" : ".";
const outfile = `${outDir}/main.js`;

/**
 * Bundles node_modules/@mediapipe/tasks-vision/wasm/vision_wasm_internal.js
 * as a plain string export so FaceDetector never fetches JS from a CDN.
 * The WASM binary and ML model (large data files) are still downloaded on
 * first use with explicit user consent.
 */
const mediapipeWasmJsBundler = {
	name: "mediapipe-wasm-js-bundler",
	setup(build) {
		const NS = "mediapipe-wasm-text";
		build.onResolve({ filter: /^mediapipe:wasm-loader$/ }, () => ({
			path: "mediapipe:wasm-loader",
			namespace: NS,
		}));
		build.onLoad({ filter: /.*/, namespace: NS }, () => {
			const wasmDir = resolve("node_modules/@mediapipe/tasks-vision/wasm");
			const js = readFileSync(`${wasmDir}/vision_wasm_internal.js`, "utf8");
			return { contents: `export default ${JSON.stringify(js)}`, loader: "js" };
		});
	},
};

/**
 * Catalog edition only: replace the focus module tree with empty stub
 * modules so none of the focus implementation (BLE child_process spawning,
 * @abandonware/noble, the device picker / calibration UI, MediaPipe /
 * FaceDetector, DetectionManager) reaches the bundle. The INCLUDE_FOCUS
 * guards in the source guarantee these stubs are never instantiated at
 * runtime. Type-only imports of focus types are erased by the TS transform
 * and need no stub.
 *
 * The stub returns an empty CommonJS module — no exports, no class
 * definitions — so the bundler's tree-shaker eliminates the entire
 * chunk when nothing reachable imports it (the dynamic imports in
 * main.ts are gated by INCLUDE_FOCUS and dead-code-eliminated).
 */
const focusStubPlugin = {
	name: "focus-stub",
	setup(build) {
		if (includeFocus) return;
		const NS = "focus-stub";
		const filter = /[\\/](ble|face|detection)[\\/][A-Za-z]+$|^\.\.\/FaceDetector$|^\.\/FaceDetector$/;
		build.onResolve({ filter }, () => ({ path: "focus-stub", namespace: NS }));
		build.onLoad({ filter: /.*/, namespace: NS }, () => ({
			contents: "module.exports={};",
			loader: "js",
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@electron/remote",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	minify: prod,
	define: {
		INCLUDE_FOCUS: JSON.stringify(includeFocus),
		// Kept for the transition; remove once source no longer references it.
		INCLUDE_BLE: JSON.stringify(includeFocus),
	},
	plugins: [focusStubPlugin, mediapipeWasmJsBundler],
});

if (prod) {
	await context.rebuild();
	// The catalog edition is a self-contained release folder: copy the
	// static plugin files alongside the freshly built main.js. The
	// catalog manifest drops the focus mentions from its description so
	// the store listing doesn't advertise a feature the bundle doesn't
	// contain, and the README loses the focus section / links so the
	// shipped plugin's docs match its actual capabilities.
	if (catalog) {
		mkdirSync(outDir, { recursive: true });
		for (const f of ["styles.css", "versions.json", "LICENSE"]) {
			try {
				copyFileSync(f, `${outDir}/${f}`);
			} catch (e) {
				console.warn(`[build] could not copy ${f}: ${e.message}`);
			}
		}
		try {
			const src = JSON.parse(readFileSync("manifest.json", "utf8"));
			src.description = "Spaced-repetition study tool with Google Calendar scheduling and AI planning via Gemini.";
			// The catalog edition strips all focus code (BLE child_process,
			// camera/MediaPipe) at build time, leaving only web-standard +
			// vault-adapter APIs — so it runs on mobile. The full edition's
			// root manifest stays desktop-only because of the focus chain.
			src.isDesktopOnly = false;
			writeFileSync(`${outDir}/manifest.json`, JSON.stringify(src, null, 2) + "\n");
		} catch (e) {
			console.warn(`[build] could not write catalog manifest.json: ${e.message}`);
		}
		try {
			const readme = readFileSync("README.md", "utf8");
			// Drop the focus detection section (and the related intro line
			// and Requirements bullets) so the shipped README matches the
			// catalog feature set. The pattern matches the heading, the
			// following bullet list (including the indented sub-bullets
			// that span multiple lines), the introductory sentence that
			// names the focus feature, and the PERFORMANCE doc link.
			const stripped = readme
				.replace(/It also includes local \*\*focus detection\*\*[^\n]*\n/, "")
				.replace(/\n- \*\*Focus detection[^\n]*\n(?:[ ]+-[^\n]*\n)+/, "\n")
				.replace(/- Obsidian desktop \(focus detection features[^\n]*\n/, "- Obsidian desktop\n")
				.replace(/- A system Node\.js installation for BLE phone detection[^\n]*\n/, "")
				.replace(/- \[`PERFORMANCE\.md`\]\([^)]*\) — Performance notes[^\n]*\n/, "");
			writeFileSync(`${outDir}/README.md`, stripped);
		} catch (e) {
			console.warn(`[build] could not write catalog README.md: ${e.message}`);
		}
		console.log(`[build] catalog edition written to ${outDir}/ (focus excluded)`);
	}
	process.exit(0);
} else {
	await context.watch();
}
